/**
 * @license
 * Copyright 2021 Google LLC. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =============================================================================
 */

// This file is autogenerated.


import {registerKernel} from '@tensorflow/tfjs-core/dist/base';
import '@tensorflow/tfjs-core/dist/base_side_effects';
export * from '@tensorflow/tfjs-core/dist/base';
export * from '@tensorflow/tfjs-converter';

//backend = cpu
export * from '@tensorflow/tfjs-backend-cpu/dist/base';
import {rangeConfig as Range_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Range';
registerKernel(Range_cpu);
import {castConfig as Cast_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Cast';
registerKernel(Cast_cpu);
import {unpackConfig as Unpack_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Unpack';
registerKernel(Unpack_cpu);
import {expandDimsConfig as ExpandDims_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/ExpandDims';
registerKernel(ExpandDims_cpu);
import {stridedSliceConfig as StridedSlice_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/StridedSlice';
registerKernel(StridedSlice_cpu);
import {lessConfig as Less_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Less';
registerKernel(Less_cpu);
import {logicalAndConfig as LogicalAnd_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/LogicalAnd';
registerKernel(LogicalAnd_cpu);
import {reshapeConfig as Reshape_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Reshape';
registerKernel(Reshape_cpu);
import {addConfig as Add_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Add';
registerKernel(Add_cpu);
import {stringSplitConfig as StringSplit_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/StringSplit';
registerKernel(StringSplit_cpu);
import {maxConfig as Max_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Max';
registerKernel(Max_cpu);
import {prodConfig as Prod_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Prod';
registerKernel(Prod_cpu);
import {greaterConfig as Greater_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Greater';
registerKernel(Greater_cpu);
import {multiplyConfig as Multiply_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Multiply';
registerKernel(Multiply_cpu);
import {maximumConfig as Maximum_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Maximum';
registerKernel(Maximum_cpu);
import {minimumConfig as Minimum_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Minimum';
registerKernel(Minimum_cpu);
import {bincountConfig as Bincount_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Bincount';
registerKernel(Bincount_cpu);
import {cumsumConfig as Cumsum_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Cumsum';
registerKernel(Cumsum_cpu);
import {concatConfig as Concat_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Concat';
registerKernel(Concat_cpu);
import {stringNGramsConfig as StringNGrams_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/StringNGrams';
registerKernel(StringNGrams_cpu);
import {packConfig as Pack_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Pack';
registerKernel(Pack_cpu);
import {notEqualConfig as NotEqual_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/NotEqual';
registerKernel(NotEqual_cpu);
import {gatherV2Config as GatherV2_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/GatherV2';
registerKernel(GatherV2_cpu);
import {sliceConfig as Slice_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Slice';
registerKernel(Slice_cpu);
import {sparseReshapeConfig as SparseReshape_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/SparseReshape';
registerKernel(SparseReshape_cpu);
import {gatherNdConfig as GatherNd_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/GatherNd';
registerKernel(GatherNd_cpu);
import {stringToHashBucketFastConfig as StringToHashBucketFast_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/StringToHashBucketFast';
registerKernel(StringToHashBucketFast_cpu);
import {greaterEqualConfig as GreaterEqual_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/GreaterEqual';
registerKernel(GreaterEqual_cpu);
import {sparseFillEmptyRowsConfig as SparseFillEmptyRows_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/SparseFillEmptyRows';
registerKernel(SparseFillEmptyRows_cpu);
import {sparseSegmentSumConfig as SparseSegmentSum_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/SparseSegmentSum';
registerKernel(SparseSegmentSum_cpu);
import {zerosLikeConfig as ZerosLike_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/ZerosLike';
registerKernel(ZerosLike_cpu);
import {tileConfig as Tile_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Tile';
registerKernel(Tile_cpu);
import {identityConfig as Identity_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Identity';
registerKernel(Identity_cpu);
import {selectConfig as Select_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Select';
registerKernel(Select_cpu);
import {sparseSegmentMeanConfig as SparseSegmentMean_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/SparseSegmentMean';
registerKernel(SparseSegmentMean_cpu);
import {_fusedMatMulConfig as _FusedMatMul_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/_FusedMatMul';
registerKernel(_FusedMatMul_cpu);
import {softmaxConfig as Softmax_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Softmax';
registerKernel(Softmax_cpu);